import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import localFont from "next/font/local";
import Footer from "../components/footer";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const caskaydiaCove = localFont({ src: "./CaskaydiaCoveNerdFontPropo-Regular.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body className={caskaydiaCove.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
