import type { Metadata } from "next";
import localFont from "next/font/local";
import Footer from "../components/footer";
import NavBar from "../components/navBar"
import "./globals.css";

const caskaydiaCove = localFont({ src: "./CaskaydiaCoveNerdFontPropo-Regular.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={caskaydiaCove.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
